### ISSUE TITLE
The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors when connecting to vRNI server.

### ISSUE THREAD

**Issue by shamantix** [PowervRNI/powervrni#25]
Hello,

I'm getting this certificate error when trying to connect to vRNI server.  Is there a way to bypass the certificate check ? -SkipCertificateCheck doesn't work.  I'm running PowerShell 7.1.4

PowerShell credential request
vRealize Network Insight Platform Authentication
User: admin@local
Password for user admin@local: *********

WARNING: Invoke-vRNIRestMethod : Exception occured calling invoke-restmethod. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
Invoke-RestMethod: J:\PowerCLI\PowervRNI.psm1:295
Line |
 295 |      $response = Invoke-RestMethod @invokeRestMethodParams
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors

**Comment by alagoutte** [comment]
it is strange because there is by default add Core version => https://github.com/PowervRNI/powervrni/blob/master/PowervRNI.psm1#L292

What do you have on $PvRNI_PlatformType variable ?

**Comment by shamantix** [comment]
If $PvRNI_PlatformType = $PSVersionTable.PSEdition,  then its Core.

PS J:\PowerCLI> $PSVersionTable.PSEdition
Core
PS J:\PowerCLI>

**Comment by shamantix** [comment]
I've tested on various PS versions from 6 to 7 with the same outcome.  Is it possible this is happening because I'm using the IP instead of a hostname when connecting the server since there is no DNS setup for it?

**Comment by smitmartijn** [comment]
> Is it possible this is happening because I'm using the IP instead of a hostname when connecting the server since there is no DNS setup for it?

That should not be the case. Could there be a system policy that disallows you to use -SkipCertificateCheck? Because Alexis is correct, PowervRNI adds the SkipCertificateCheck option by default (because 95% of people use a self-signed cert).

What happens if you set your terminal session to ignore certificate checks, and then run Connect-vRNIServer?

```
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
Connect-vRNIServer -Server etc..
```

**Comment by shamantix** [comment]
> > Is it possible this is happening because I'm using the IP instead of a hostname when connecting the server since there is no DNS setup for it?
> 
> That should not be the case. Could there be a system policy that disallows you to use -SkipCertificateCheck? Because Alexis is correct, PowervRNI adds the SkipCertificateCheck option by default (because 95% of people use a self-signed cert).
> 
> What happens if you set your terminal session to ignore certificate checks, and then run Connect-vRNIServer?
> 
> ```
> [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
> Connect-vRNIServer -Server etc..
> ```
Same result. :(

This time around I've also tried to connect from a Linux box to rule out this isn't caused by the System Policy on the Windows machine and got the same error.

Btw, the vRNI version I'm trying to connect to is 6.3.

----
Centos 8, Powershell version 7.1.4:

PowerShell credential request
vRealize Network Insight Platform Authentication
User: admin@local
Password for user admin@local: *********

WARNING: Invoke-vRNIRestMethod : Exception occured calling invoke-restmethod. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization) in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs:line 1361
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord() in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs:line 1518
Invoke-RestMethod: /home/user/Downloads/PowervRNI.psm1:295
Line |
 295 |      $response = Invoke-RestMethod @invokeRestMethodParams
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors

**Comment by smitmartijn** [comment]
I can't reproduce this on macOS or Windows with PowerShell 7.1.4 against a vRNI instance with a hostname or without. I don't know what could be causing this to fail on your setup, but it doesn't seem to be a PowervRNI issue.

Some final suggestions: try to use a hostname, even it's just in your /etc/hosts file. Maybe also try to add a new certificate to vRNI.

**Comment by shamantix** [comment]
> 
> 
> I can't reproduce this on macOS or Windows with PowerShell 7.1.4 against a vRNI instance with a hostname or without. I don't know what could be causing this to fail on your setup, but it doesn't seem to be a PowervRNI issue.
> 
> Some final suggestions: try to use a hostname, even it's just in your /etc/hosts file. Maybe also try to add a new certificate to vRNI.

What version of vRNI are you running?
